### ISSUE TITLE
Add `.isEnabled` getter/setter

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/KeyboardShortcuts#108]
To temporarily disable/enable all keyboard shortcuts.

See: https://github.com/sindresorhus/KeyboardShortcuts/pull/107#issuecomment-1295829557

**Comment by iSapozhnik** [comment]
I might work on this PR since I was initially the one who requested it. Quick question though... So the logic would be the following. By setting `true` or `false` to the `.isEnabled` property I would need to iterate through all registered shortcuts and then either disable or enable them, right? Or there is anything else I would need to take care of?
